<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Job;

/**
 * JobsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobsRepository extends EntityRepository
{

    public function getJobsQuery(Category $category = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb
                ->select('j')
                ->from('AppBundle:Job', 'j');
        if ($category) {
            $qb->where('j.category = :category')
                    ->setParameter('category', $category);
        }
        $qb->orderBy('j.publishedAt', 'DESC');
        return $qb->getQuery();
    }
}
