<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobsRepository extends EntityRepository
{

    public function getJobsQuery(Category $category = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb
                ->select('j', 'c')
                ->from('AppBundle:Job', 'j')
                ->innerJoin('j.category', 'c')
                ->where('j.verified = true')
                ->andWhere('c.enabled = true');
        if ($category) {
            $qb->andWhere('j.category = :category')
                    ->setParameter('category', $category);
        }
        $qb->orderBy('j.publishedAt', 'DESC');
        return $qb->getQuery();
    }

}
